# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sfarm_gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(912, 580)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("border-width:1px")
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(170, 0, 741, 571))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.stackedWidget.setFont(font)
        self.stackedWidget.setStyleSheet("background-color : rgb(255,255,255)")
        self.stackedWidget.setObjectName("stackedWidget")
        self.managePage = QtWidgets.QWidget()
        self.managePage.setObjectName("managePage")
        self.viewWater = PlotWidget(self.managePage)
        self.viewWater.setGeometry(QtCore.QRect(20, 300, 591, 150))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.viewWater.setFont(font)
        self.viewWater.setObjectName("viewWater")
        self.labelCondition = QtWidgets.QLabel(self.managePage)
        self.labelCondition.setGeometry(QtCore.QRect(20, 470, 65, 19))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        self.labelCondition.setFont(font)
        self.labelCondition.setObjectName("labelCondition")
        self.labelWater = QtWidgets.QLabel(self.managePage)
        self.labelWater.setGeometry(QtCore.QRect(20, 280, 101, 19))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        self.labelWater.setFont(font)
        self.labelWater.setObjectName("labelWater")
        self.labelAir = QtWidgets.QLabel(self.managePage)
        self.labelAir.setGeometry(QtCore.QRect(20, 10, 81, 19))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        self.labelAir.setFont(font)
        self.labelAir.setTextFormat(QtCore.Qt.PlainText)
        self.labelAir.setObjectName("labelAir")
        self.viewAir = PlotWidget(self.managePage)
        self.viewAir.setGeometry(QtCore.QRect(20, 40, 591, 211))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.viewAir.setFont(font)
        self.viewAir.setObjectName("viewAir")
        self.viewCondition = PlotWidget(self.managePage)
        self.viewCondition.setGeometry(QtCore.QRect(20, 490, 591, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.viewCondition.setFont(font)
        self.viewCondition.setObjectName("viewCondition")
        self.buttonSave = QtWidgets.QPushButton(self.managePage)
        self.buttonSave.setGeometry(QtCore.QRect(670, 510, 41, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.buttonSave.setFont(font)
        self.buttonSave.setStyleSheet("background-color: rgb(220,220,220)")
        self.buttonSave.setObjectName("buttonSave")
        self.spinBoxResult = QtWidgets.QSpinBox(self.managePage)
        self.spinBoxResult.setGeometry(QtCore.QRect(620, 510, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.spinBoxResult.setFont(font)
        self.spinBoxResult.setMinimum(1)
        self.spinBoxResult.setMaximum(5)
        self.spinBoxResult.setProperty("value", 3)
        self.spinBoxResult.setObjectName("spinBoxResult")
        self.labelResult = QtWidgets.QLabel(self.managePage)
        self.labelResult.setGeometry(QtCore.QRect(620, 490, 56, 12))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.labelResult.setFont(font)
        self.labelResult.setObjectName("labelResult")
        self.groupBox = QtWidgets.QGroupBox(self.managePage)
        self.groupBox.setGeometry(QtCore.QRect(620, 40, 101, 211))
        self.groupBox.setInputMethodHints(QtCore.Qt.ImhNone)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.checkboxCo2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkboxCo2.setGeometry(QtCore.QRect(10, 10, 48, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.checkboxCo2.setFont(font)
        self.checkboxCo2.setChecked(True)
        self.checkboxCo2.setObjectName("checkboxCo2")
        self.checkboxHumid = QtWidgets.QCheckBox(self.groupBox)
        self.checkboxHumid.setGeometry(QtCore.QRect(10, 70, 65, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.checkboxHumid.setFont(font)
        self.checkboxHumid.setChecked(True)
        self.checkboxHumid.setObjectName("checkboxHumid")
        self.checkboxTemp = QtWidgets.QCheckBox(self.groupBox)
        self.checkboxTemp.setGeometry(QtCore.QRect(10, 130, 58, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.checkboxTemp.setFont(font)
        self.checkboxTemp.setChecked(True)
        self.checkboxTemp.setObjectName("checkboxTemp")
        self.Co2Display = QtWidgets.QLCDNumber(self.groupBox)
        self.Co2Display.setGeometry(QtCore.QRect(10, 30, 64, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.Co2Display.setFont(font)
        self.Co2Display.setStyleSheet("")
        self.Co2Display.setObjectName("Co2Display")
        self.HumidDisplay = QtWidgets.QLCDNumber(self.groupBox)
        self.HumidDisplay.setGeometry(QtCore.QRect(10, 90, 64, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.HumidDisplay.setFont(font)
        self.HumidDisplay.setObjectName("HumidDisplay")
        self.TempDisplay = QtWidgets.QLCDNumber(self.groupBox)
        self.TempDisplay.setGeometry(QtCore.QRect(10, 150, 64, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.TempDisplay.setFont(font)
        self.TempDisplay.setObjectName("TempDisplay")
        self.labelPercent_4 = QtWidgets.QLabel(self.groupBox)
        self.labelPercent_4.setGeometry(QtCore.QRect(80, 90, 11, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.labelPercent_4.setFont(font)
        self.labelPercent_4.setObjectName("labelPercent_4")
        self.labelCelcius_2 = QtWidgets.QLabel(self.groupBox)
        self.labelCelcius_2.setGeometry(QtCore.QRect(80, 150, 13, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.labelCelcius_2.setFont(font)
        self.labelCelcius_2.setObjectName("labelCelcius_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.managePage)
        self.groupBox_2.setGeometry(QtCore.QRect(620, 300, 101, 151))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.checkboxTDS = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkboxTDS.setGeometry(QtCore.QRect(10, 10, 48, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.checkboxTDS.setFont(font)
        self.checkboxTDS.setChecked(True)
        self.checkboxTDS.setObjectName("checkboxTDS")
        self.TDSDisplay = QtWidgets.QLCDNumber(self.groupBox_2)
        self.TDSDisplay.setGeometry(QtCore.QRect(10, 30, 64, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.TDSDisplay.setFont(font)
        self.TDSDisplay.setObjectName("TDSDisplay")
        self.checkboxPH = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkboxPH.setGeometry(QtCore.QRect(10, 70, 41, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.checkboxPH.setFont(font)
        self.checkboxPH.setChecked(True)
        self.checkboxPH.setObjectName("checkboxPH")
        self.PHDisplay = QtWidgets.QLCDNumber(self.groupBox_2)
        self.PHDisplay.setGeometry(QtCore.QRect(10, 90, 64, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.PHDisplay.setFont(font)
        self.PHDisplay.setObjectName("PHDisplay")
        self.stackedWidget.addWidget(self.managePage)
        self.settingsPage = QtWidgets.QWidget()
        self.settingsPage.setObjectName("settingsPage")
        self.buttonApply = QtWidgets.QPushButton(self.settingsPage)
        self.buttonApply.setGeometry(QtCore.QRect(600, 460, 95, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonApply.sizePolicy().hasHeightForWidth())
        self.buttonApply.setSizePolicy(sizePolicy)
        self.buttonApply.setMinimumSize(QtCore.QSize(0, 0))
        self.buttonApply.setMaximumSize(QtCore.QSize(95, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.buttonApply.setFont(font)
        self.buttonApply.setStyleSheet("background-color: rgb(220,220,220)")
        self.buttonApply.setObjectName("buttonApply")
        self.buttonRevert = QtWidgets.QPushButton(self.settingsPage)
        self.buttonRevert.setGeometry(QtCore.QRect(600, 490, 95, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonRevert.sizePolicy().hasHeightForWidth())
        self.buttonRevert.setSizePolicy(sizePolicy)
        self.buttonRevert.setMinimumSize(QtCore.QSize(0, 0))
        self.buttonRevert.setMaximumSize(QtCore.QSize(95, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.buttonRevert.setFont(font)
        self.buttonRevert.setStyleSheet("background-color: rgb(220,220,220)")
        self.buttonRevert.setObjectName("buttonRevert")
        self.layoutWidget = QtWidgets.QWidget(self.settingsPage)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 50, 171, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout_8 = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout_8.setContentsMargins(0, 0, 0, 0)
        self.formLayout_8.setObjectName("formLayout_8")
        self.labelCo2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        self.labelCo2.setFont(font)
        self.labelCo2.setObjectName("labelCo2")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelCo2)
        self.spinBoxCo2 = QtWidgets.QSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxCo2.sizePolicy().hasHeightForWidth())
        self.spinBoxCo2.setSizePolicy(sizePolicy)
        self.spinBoxCo2.setMinimumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.spinBoxCo2.setFont(font)
        self.spinBoxCo2.setMinimum(800)
        self.spinBoxCo2.setMaximum(2000)
        self.spinBoxCo2.setSingleStep(100)
        self.spinBoxCo2.setObjectName("spinBoxCo2")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.spinBoxCo2)
        self.buttonCo2 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonCo2.sizePolicy().hasHeightForWidth())
        self.buttonCo2.setSizePolicy(sizePolicy)
        self.buttonCo2.setMinimumSize(QtCore.QSize(0, 0))
        self.buttonCo2.setMaximumSize(QtCore.QSize(95, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.buttonCo2.setFont(font)
        self.buttonCo2.setStyleSheet("background-color: rgb(235, 235, 235)")
        self.buttonCo2.setObjectName("buttonCo2")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.buttonCo2)
        self.layoutWidget1 = QtWidgets.QWidget(self.settingsPage)
        self.layoutWidget1.setGeometry(QtCore.QRect(210, 50, 171, 61))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.formLayout_9 = QtWidgets.QFormLayout(self.layoutWidget1)
        self.formLayout_9.setContentsMargins(0, 0, 0, 0)
        self.formLayout_9.setObjectName("formLayout_9")
        self.labelHumid = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        self.labelHumid.setFont(font)
        self.labelHumid.setObjectName("labelHumid")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelHumid)
        self.buttonHumid = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonHumid.sizePolicy().hasHeightForWidth())
        self.buttonHumid.setSizePolicy(sizePolicy)
        self.buttonHumid.setMinimumSize(QtCore.QSize(0, 0))
        self.buttonHumid.setMaximumSize(QtCore.QSize(95, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.buttonHumid.setFont(font)
        self.buttonHumid.setStyleSheet("background-color: rgb(235, 235, 235)")
        self.buttonHumid.setObjectName("buttonHumid")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.buttonHumid)
        self.formLayout_12 = QtWidgets.QFormLayout()
        self.formLayout_12.setObjectName("formLayout_12")
        self.spinBoxHumid = QtWidgets.QSpinBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxHumid.sizePolicy().hasHeightForWidth())
        self.spinBoxHumid.setSizePolicy(sizePolicy)
        self.spinBoxHumid.setMinimumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.spinBoxHumid.setFont(font)
        self.spinBoxHumid.setProperty("value", 20)
        self.spinBoxHumid.setObjectName("spinBoxHumid")
        self.formLayout_12.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.spinBoxHumid)
        self.labelPercent = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.labelPercent.setFont(font)
        self.labelPercent.setObjectName("labelPercent")
        self.formLayout_12.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.labelPercent)
        self.formLayout_9.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.formLayout_12)
        self.layoutWidget2 = QtWidgets.QWidget(self.settingsPage)
        self.layoutWidget2.setGeometry(QtCore.QRect(200, 270, 124, 58))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget2)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.labelPH = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        self.labelPH.setFont(font)
        self.labelPH.setObjectName("labelPH")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelPH)
        self.formLayout_16 = QtWidgets.QFormLayout()
        self.formLayout_16.setObjectName("formLayout_16")
        self.sliderPH = QtWidgets.QSlider(self.layoutWidget2)
        self.sliderPH.setMinimumSize(QtCore.QSize(100, 0))
        self.sliderPH.setMaximum(14)
        self.sliderPH.setPageStep(1)
        self.sliderPH.setProperty("value", 5)
        self.sliderPH.setOrientation(QtCore.Qt.Horizontal)
        self.sliderPH.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.sliderPH.setObjectName("sliderPH")
        self.formLayout_16.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.sliderPH)
        self.labelPH_2 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.labelPH_2.setFont(font)
        self.labelPH_2.setObjectName("labelPH_2")
        self.formLayout_16.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.labelPH_2)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.formLayout_16)
        self.layoutWidget3 = QtWidgets.QWidget(self.settingsPage)
        self.layoutWidget3.setGeometry(QtCore.QRect(30, 270, 151, 61))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.layoutWidget3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.labelTDS = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        self.labelTDS.setFont(font)
        self.labelTDS.setObjectName("labelTDS")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelTDS)
        self.formLayout_17 = QtWidgets.QFormLayout()
        self.formLayout_17.setObjectName("formLayout_17")
        self.sliderTDS = QtWidgets.QSlider(self.layoutWidget3)
        self.sliderTDS.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.sliderTDS.setFont(font)
        self.sliderTDS.setMaximum(1500)
        self.sliderTDS.setSingleStep(150)
        self.sliderTDS.setPageStep(150)
        self.sliderTDS.setProperty("value", 1000)
        self.sliderTDS.setOrientation(QtCore.Qt.Horizontal)
        self.sliderTDS.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.sliderTDS.setObjectName("sliderTDS")
        self.formLayout_17.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.sliderTDS)
        self.labelTDS_2 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.labelTDS_2.setFont(font)
        self.labelTDS_2.setObjectName("labelTDS_2")
        self.formLayout_17.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.labelTDS_2)
        self.formLayout_3.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.formLayout_17)
        self.layoutWidget4 = QtWidgets.QWidget(self.settingsPage)
        self.layoutWidget4.setGeometry(QtCore.QRect(30, 370, 209, 61))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.formLayout_7 = QtWidgets.QFormLayout(self.layoutWidget4)
        self.formLayout_7.setContentsMargins(0, 0, 0, 0)
        self.formLayout_7.setObjectName("formLayout_7")
        self.labelPump = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        self.labelPump.setFont(font)
        self.labelPump.setObjectName("labelPump")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelPump)
        self.formLayout_13 = QtWidgets.QFormLayout()
        self.formLayout_13.setObjectName("formLayout_13")
        self.spinBoxPump = QtWidgets.QSpinBox(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxPump.sizePolicy().hasHeightForWidth())
        self.spinBoxPump.setSizePolicy(sizePolicy)
        self.spinBoxPump.setMinimumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.spinBoxPump.setFont(font)
        self.spinBoxPump.setMinimum(1)
        self.spinBoxPump.setMaximum(100)
        self.spinBoxPump.setProperty("value", 100)
        self.spinBoxPump.setObjectName("spinBoxPump")
        self.formLayout_13.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.spinBoxPump)
        self.labelPercent_3 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.labelPercent_3.setFont(font)
        self.labelPercent_3.setObjectName("labelPercent_3")
        self.formLayout_13.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.labelPercent_3)
        self.formLayout_7.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.formLayout_13)
        self.buttonPump = QtWidgets.QPushButton(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonPump.sizePolicy().hasHeightForWidth())
        self.buttonPump.setSizePolicy(sizePolicy)
        self.buttonPump.setMinimumSize(QtCore.QSize(0, 0))
        self.buttonPump.setMaximumSize(QtCore.QSize(95, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.buttonPump.setFont(font)
        self.buttonPump.setStyleSheet("background-color: rgb(235, 235, 235)")
        self.buttonPump.setObjectName("buttonPump")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.buttonPump)
        self.labelAir_2 = QtWidgets.QLabel(self.settingsPage)
        self.labelAir_2.setGeometry(QtCore.QRect(20, 10, 81, 19))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        self.labelAir_2.setFont(font)
        self.labelAir_2.setTextFormat(QtCore.Qt.PlainText)
        self.labelAir_2.setObjectName("labelAir_2")
        self.labelWater_2 = QtWidgets.QLabel(self.settingsPage)
        self.labelWater_2.setGeometry(QtCore.QRect(20, 230, 101, 19))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        self.labelWater_2.setFont(font)
        self.labelWater_2.setObjectName("labelWater_2")
        self.lableLight = QtWidgets.QLabel(self.settingsPage)
        self.lableLight.setGeometry(QtCore.QRect(410, 230, 101, 19))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        self.lableLight.setFont(font)
        self.lableLight.setObjectName("lableLight")
        self.layoutWidget5 = QtWidgets.QWidget(self.settingsPage)
        self.layoutWidget5.setGeometry(QtCore.QRect(30, 130, 89, 57))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.formLayout_4 = QtWidgets.QFormLayout(self.layoutWidget5)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.formLayout_14 = QtWidgets.QFormLayout()
        self.formLayout_14.setObjectName("formLayout_14")
        self.spinBoxTemp = QtWidgets.QDoubleSpinBox(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxTemp.sizePolicy().hasHeightForWidth())
        self.spinBoxTemp.setSizePolicy(sizePolicy)
        self.spinBoxTemp.setMinimumSize(QtCore.QSize(25, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.spinBoxTemp.setFont(font)
        self.spinBoxTemp.setMaximum(50.0)
        self.spinBoxTemp.setProperty("value", 25.0)
        self.spinBoxTemp.setObjectName("spinBoxTemp")
        self.formLayout_14.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.spinBoxTemp)
        self.labelCelcius = QtWidgets.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.labelCelcius.setFont(font)
        self.labelCelcius.setObjectName("labelCelcius")
        self.formLayout_14.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.labelCelcius)
        self.formLayout_4.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.formLayout_14)
        self.labelTemp = QtWidgets.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        self.labelTemp.setFont(font)
        self.labelTemp.setObjectName("labelTemp")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelTemp)
        self.layoutWidget6 = QtWidgets.QWidget(self.settingsPage)
        self.layoutWidget6.setGeometry(QtCore.QRect(130, 130, 181, 54))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.formLayout_5 = QtWidgets.QFormLayout(self.layoutWidget6)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.labelFan = QtWidgets.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        font.setItalic(False)
        self.labelFan.setFont(font)
        self.labelFan.setObjectName("labelFan")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelFan)
        self.formLayout_15 = QtWidgets.QFormLayout()
        self.formLayout_15.setObjectName("formLayout_15")
        self.spinBoxFan = QtWidgets.QSpinBox(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxFan.sizePolicy().hasHeightForWidth())
        self.spinBoxFan.setSizePolicy(sizePolicy)
        self.spinBoxFan.setMinimumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.spinBoxFan.setFont(font)
        self.spinBoxFan.setMinimum(1)
        self.spinBoxFan.setMaximum(100)
        self.spinBoxFan.setProperty("value", 100)
        self.spinBoxFan.setObjectName("spinBoxFan")
        self.formLayout_15.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.spinBoxFan)
        self.labelPercent_2 = QtWidgets.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.labelPercent_2.setFont(font)
        self.labelPercent_2.setObjectName("labelPercent_2")
        self.formLayout_15.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.labelPercent_2)
        self.formLayout_5.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.formLayout_15)
        self.buttonFan = QtWidgets.QPushButton(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonFan.sizePolicy().hasHeightForWidth())
        self.buttonFan.setSizePolicy(sizePolicy)
        self.buttonFan.setMinimumSize(QtCore.QSize(0, 0))
        self.buttonFan.setMaximumSize(QtCore.QSize(95, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.buttonFan.setFont(font)
        self.buttonFan.setStyleSheet("background-color: rgb(235, 235, 235)")
        self.buttonFan.setObjectName("buttonFan")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.buttonFan)
        self.buttonFan.raise_()
        self.labelFan.raise_()
        self.layoutWidget7 = QtWidgets.QWidget(self.settingsPage)
        self.layoutWidget7.setGeometry(QtCore.QRect(420, 270, 255, 171))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.formLayout_10 = QtWidgets.QFormLayout(self.layoutWidget7)
        self.formLayout_10.setContentsMargins(0, 0, 0, 0)
        self.formLayout_10.setObjectName("formLayout_10")
        self.labelLED = QtWidgets.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        self.labelLED.setFont(font)
        self.labelLED.setObjectName("labelLED")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelLED)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelB = QtWidgets.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.labelB.setFont(font)
        self.labelB.setObjectName("labelB")
        self.gridLayout_2.addWidget(self.labelB, 0, 2, 1, 1)
        self.labelW = QtWidgets.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.labelW.setFont(font)
        self.labelW.setObjectName("labelW")
        self.gridLayout_2.addWidget(self.labelW, 0, 3, 1, 1)
        self.labelG = QtWidgets.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.labelG.setFont(font)
        self.labelG.setObjectName("labelG")
        self.gridLayout_2.addWidget(self.labelG, 0, 1, 1, 1)
        self.labelR = QtWidgets.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.labelR.setFont(font)
        self.labelR.setObjectName("labelR")
        self.gridLayout_2.addWidget(self.labelR, 0, 0, 1, 1)
        self.sliderW = QtWidgets.QSlider(self.layoutWidget7)
        self.sliderW.setMinimumSize(QtCore.QSize(0, 80))
        self.sliderW.setAutoFillBackground(False)
        self.sliderW.setMaximum(255)
        self.sliderW.setSingleStep(25)
        self.sliderW.setPageStep(25)
        self.sliderW.setProperty("value", 125)
        self.sliderW.setOrientation(QtCore.Qt.Vertical)
        self.sliderW.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.sliderW.setObjectName("sliderW")
        self.gridLayout_2.addWidget(self.sliderW, 1, 3, 1, 1)
        self.sliderG = QtWidgets.QSlider(self.layoutWidget7)
        self.sliderG.setMinimumSize(QtCore.QSize(0, 80))
        self.sliderG.setMaximum(255)
        self.sliderG.setSingleStep(25)
        self.sliderG.setPageStep(25)
        self.sliderG.setProperty("value", 0)
        self.sliderG.setOrientation(QtCore.Qt.Vertical)
        self.sliderG.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.sliderG.setObjectName("sliderG")
        self.gridLayout_2.addWidget(self.sliderG, 1, 1, 1, 1)
        self.sliderB = QtWidgets.QSlider(self.layoutWidget7)
        self.sliderB.setMinimumSize(QtCore.QSize(0, 80))
        self.sliderB.setAutoFillBackground(False)
        self.sliderB.setMaximum(255)
        self.sliderB.setSingleStep(25)
        self.sliderB.setPageStep(25)
        self.sliderB.setProperty("value", 125)
        self.sliderB.setOrientation(QtCore.Qt.Vertical)
        self.sliderB.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.sliderB.setObjectName("sliderB")
        self.gridLayout_2.addWidget(self.sliderB, 1, 2, 1, 1)
        self.labelG_2 = QtWidgets.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.labelG_2.setFont(font)
        self.labelG_2.setObjectName("labelG_2")
        self.gridLayout_2.addWidget(self.labelG_2, 2, 1, 1, 1)
        self.labelB_2 = QtWidgets.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.labelB_2.setFont(font)
        self.labelB_2.setStyleSheet("text-align: center;")
        self.labelB_2.setObjectName("labelB_2")
        self.gridLayout_2.addWidget(self.labelB_2, 2, 2, 1, 1)
        self.labelW_2 = QtWidgets.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.labelW_2.setFont(font)
        self.labelW_2.setStyleSheet("text-align: center;")
        self.labelW_2.setObjectName("labelW_2")
        self.gridLayout_2.addWidget(self.labelW_2, 2, 3, 1, 1)
        self.sliderR = QtWidgets.QSlider(self.layoutWidget7)
        self.sliderR.setMinimumSize(QtCore.QSize(0, 80))
        self.sliderR.setStyleSheet("")
        self.sliderR.setMaximum(255)
        self.sliderR.setSingleStep(25)
        self.sliderR.setPageStep(25)
        self.sliderR.setProperty("value", 125)
        self.sliderR.setOrientation(QtCore.Qt.Vertical)
        self.sliderR.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.sliderR.setObjectName("sliderR")
        self.gridLayout_2.addWidget(self.sliderR, 1, 0, 1, 1)
        self.labelR_2 = QtWidgets.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.labelR_2.setFont(font)
        self.labelR_2.setStyleSheet("text-align: center;")
        self.labelR_2.setObjectName("labelR_2")
        self.gridLayout_2.addWidget(self.labelR_2, 2, 0, 1, 1)
        self.formLayout_10.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.gridLayout_2)
        self.buttonLED = QtWidgets.QPushButton(self.layoutWidget7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonLED.sizePolicy().hasHeightForWidth())
        self.buttonLED.setSizePolicy(sizePolicy)
        self.buttonLED.setMinimumSize(QtCore.QSize(0, 0))
        self.buttonLED.setMaximumSize(QtCore.QSize(95, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.buttonLED.setFont(font)
        self.buttonLED.setStyleSheet("background-color: rgb(235, 235, 235)")
        self.buttonLED.setObjectName("buttonLED")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.buttonLED)
        self.line_3 = QtWidgets.QFrame(self.settingsPage)
        self.line_3.setGeometry(QtCore.QRect(10, 260, 20, 191))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.settingsPage)
        self.line_4.setGeometry(QtCore.QRect(10, 40, 20, 161))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_6 = QtWidgets.QFrame(self.settingsPage)
        self.line_6.setGeometry(QtCore.QRect(380, 260, 20, 191))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.settingsPage)
        self.line_7.setGeometry(QtCore.QRect(400, 260, 20, 191))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.settingsPage)
        self.line_8.setGeometry(QtCore.QRect(680, 260, 20, 191))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.settingsPage)
        self.line_9.setGeometry(QtCore.QRect(20, 260, 371, 3))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.settingsPage)
        self.line_10.setGeometry(QtCore.QRect(20, 450, 371, 3))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(self.settingsPage)
        self.line_11.setGeometry(QtCore.QRect(410, 450, 281, 3))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(self.settingsPage)
        self.line_12.setGeometry(QtCore.QRect(410, 260, 281, 3))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_13 = QtWidgets.QFrame(self.settingsPage)
        self.line_13.setGeometry(QtCore.QRect(20, 200, 371, 2))
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.line_14 = QtWidgets.QFrame(self.settingsPage)
        self.line_14.setGeometry(QtCore.QRect(20, 40, 371, 2))
        self.line_14.setMaximumSize(QtCore.QSize(16777215, 3))
        self.line_14.setStyleSheet("")
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.line_5 = QtWidgets.QFrame(self.settingsPage)
        self.line_5.setGeometry(QtCore.QRect(380, 40, 20, 161))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_5.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.buttonApply.raise_()
        self.buttonRevert.raise_()
        self.layoutWidget.raise_()
        self.labelAir_2.raise_()
        self.labelWater_2.raise_()
        self.lableLight.raise_()
        self.line_3.raise_()
        self.line_4.raise_()
        self.line_6.raise_()
        self.line_7.raise_()
        self.line_8.raise_()
        self.line_9.raise_()
        self.line_10.raise_()
        self.line_11.raise_()
        self.line_12.raise_()
        self.line_14.raise_()
        self.line_13.raise_()
        self.stackedWidget.addWidget(self.settingsPage)
        self.viewLogo = QtWidgets.QGraphicsView(self.centralwidget)
        self.viewLogo.setGeometry(QtCore.QRect(0, 0, 170, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewLogo.sizePolicy().hasHeightForWidth())
        self.viewLogo.setSizePolicy(sizePolicy)
        self.viewLogo.setMaximumSize(QtCore.QSize(170, 50))
        self.viewLogo.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.viewLogo.setFont(font)
        self.viewLogo.setStyleSheet("background-image: url(:/imgsources/prelogodesign.png);\n"
"border:transparent\n"
"")
        self.viewLogo.setObjectName("viewLogo")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 50, 170, 3))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMaximumSize(QtCore.QSize(170, 3))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(160, 0, 20, 561))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.layoutWidget8 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget8.setGeometry(QtCore.QRect(20, 60, 115, 34))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.formLayout_6 = QtWidgets.QFormLayout(self.layoutWidget8)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.ViewMIcon = QtWidgets.QGraphicsView(self.layoutWidget8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ViewMIcon.sizePolicy().hasHeightForWidth())
        self.ViewMIcon.setSizePolicy(sizePolicy)
        self.ViewMIcon.setMaximumSize(QtCore.QSize(32, 32))
        self.ViewMIcon.setStyleSheet("background-image : url(:/imgsources/chart.png);\n"
"border:transparent")
        self.ViewMIcon.setObjectName("ViewMIcon")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.ViewMIcon)
        self.buttonManage = QtWidgets.QPushButton(self.layoutWidget8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonManage.sizePolicy().hasHeightForWidth())
        self.buttonManage.setSizePolicy(sizePolicy)
        self.buttonManage.setMinimumSize(QtCore.QSize(0, 0))
        self.buttonManage.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.buttonManage.setFont(font)
        self.buttonManage.setStyleSheet("background-color : rgba(10, 255, 0,0 )")
        self.buttonManage.setDefault(True)
        self.buttonManage.setObjectName("buttonManage")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.buttonManage)
        self.layoutWidget9 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget9.setGeometry(QtCore.QRect(20, 100, 117, 36))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.formLayout_2 = QtWidgets.QFormLayout(self.layoutWidget9)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.buttonSettings = QtWidgets.QPushButton(self.layoutWidget9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonSettings.sizePolicy().hasHeightForWidth())
        self.buttonSettings.setSizePolicy(sizePolicy)
        self.buttonSettings.setMinimumSize(QtCore.QSize(0, 0))
        self.buttonSettings.setMaximumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.buttonSettings.setFont(font)
        self.buttonSettings.setStyleSheet("background-color : rgba(10, 255, 0, 0)")
        self.buttonSettings.setObjectName("buttonSettings")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.buttonSettings)
        self.ViewSIcon = QtWidgets.QGraphicsView(self.layoutWidget9)
        self.ViewSIcon.setMaximumSize(QtCore.QSize(34, 34))
        self.ViewSIcon.setStyleSheet("background-image : url(:/imgsources/repairing.png);\n"
"border: transparent")
        self.ViewSIcon.setObjectName("ViewSIcon")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.ViewSIcon)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.sliderR.valueChanged['int'].connect(self.labelR_2.setNum)
        self.sliderG.valueChanged['int'].connect(self.labelG_2.setNum)
        self.sliderB.valueChanged['int'].connect(self.labelB_2.setNum)
        self.sliderW.valueChanged['int'].connect(self.labelW_2.setNum)
        self.sliderTDS.valueChanged['int'].connect(self.labelTDS_2.setNum)
        self.sliderPH.valueChanged['int'].connect(self.labelPH_2.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SmartFarm"))
        self.labelCondition.setText(_translate("MainWindow", "Conditon"))
        self.labelWater.setText(_translate("MainWindow", "Water Quality"))
        self.labelAir.setText(_translate("MainWindow", "Air Quality"))
        self.buttonSave.setText(_translate("MainWindow", "save"))
        self.labelResult.setText(_translate("MainWindow", "Result"))
        self.checkboxCo2.setText(_translate("MainWindow", "Co2"))
        self.checkboxHumid.setText(_translate("MainWindow", "Humid"))
        self.checkboxTemp.setText(_translate("MainWindow", "Temp"))
        self.labelPercent_4.setText(_translate("MainWindow", "%"))
        self.labelCelcius_2.setText(_translate("MainWindow", "°C"))
        self.checkboxTDS.setText(_translate("MainWindow", "TDS"))
        self.checkboxPH.setText(_translate("MainWindow", "PH"))
        self.buttonApply.setText(_translate("MainWindow", "apply"))
        self.buttonRevert.setText(_translate("MainWindow", "revert"))
        self.labelCo2.setText(_translate("MainWindow", "Co2"))
        self.buttonCo2.setText(_translate("MainWindow", "stop"))
        self.labelHumid.setText(_translate("MainWindow", "Humid"))
        self.buttonHumid.setText(_translate("MainWindow", "stop"))
        self.labelPercent.setText(_translate("MainWindow", "%"))
        self.labelPH.setText(_translate("MainWindow", "PH"))
        self.labelPH_2.setText(_translate("MainWindow", "5"))
        self.labelTDS.setText(_translate("MainWindow", "TDS"))
        self.labelTDS_2.setText(_translate("MainWindow", "1000"))
        self.labelPump.setText(_translate("MainWindow", "Pump"))
        self.labelPercent_3.setText(_translate("MainWindow", "%"))
        self.buttonPump.setText(_translate("MainWindow", "stop"))
        self.labelAir_2.setText(_translate("MainWindow", "Air "))
        self.labelWater_2.setText(_translate("MainWindow", "Water"))
        self.lableLight.setText(_translate("MainWindow", "Light"))
        self.labelCelcius.setText(_translate("MainWindow", "°C"))
        self.labelTemp.setText(_translate("MainWindow", "Temp"))
        self.labelFan.setText(_translate("MainWindow", "Fan"))
        self.labelPercent_2.setText(_translate("MainWindow", "%"))
        self.buttonFan.setText(_translate("MainWindow", "stop"))
        self.labelLED.setText(_translate("MainWindow", "LED"))
        self.labelB.setText(_translate("MainWindow", "B"))
        self.labelW.setText(_translate("MainWindow", "W"))
        self.labelG.setText(_translate("MainWindow", "G"))
        self.labelR.setText(_translate("MainWindow", "R"))
        self.labelG_2.setText(_translate("MainWindow", "0"))
        self.labelB_2.setText(_translate("MainWindow", "125"))
        self.labelW_2.setText(_translate("MainWindow", "125"))
        self.labelR_2.setText(_translate("MainWindow", "125"))
        self.buttonLED.setText(_translate("MainWindow", "stop"))
        self.buttonManage.setText(_translate("MainWindow", "Manage"))
        self.buttonSettings.setText(_translate("MainWindow", "Settings"))

from pyqtgraph import PlotWidget
import sources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

